######################################################################
# Automatically generated by qmake (3.0) lun lug 24 14:05:56 2017
######################################################################

TEMPLATE = app
TARGET = DocSpeacker
INCLUDEPATH += .

# Input
HEADERS += require/opendoc/basic_helper.h \
           require/opendoc/GZipReader.h \
           require/opendoc/GZipWriter.h \
           require/opendoc/OOFormat.h \
           require/opendoc/OOReader.h \
           require/patch_qt4.5/qtextodfwriter_p.h \
           require/qtpdfium/src/pdfium/qpdfium.h \
           require/qtpdfium/src/pdfium/qpdfiumglobal.h \
           require/qtpdfium/src/pdfium/qpdfiumpage.h \
           require/qtspeech/include/QtTextToSpeech/qtexttospeech.h \
           require/qtspeech/include/QtTextToSpeech/qtexttospeech_global.h \
           require/qtspeech/include/QtTextToSpeech/qtexttospeechengine.h \
           require/qtspeech/include/QtTextToSpeech/qtexttospeechplugin.h \
           require/qtspeech/include/QtTextToSpeech/qttexttospeechversion.h \
           require/qtspeech/include/QtTextToSpeech/qvoice.h
SOURCES += require/opendoc/basic_helper.cpp \
           require/opendoc/GZip.cpp \
           require/opendoc/OOFormat.cpp \
           require/opendoc/OOReader.cpp \
           require/patch_qt4.5/qtextodfwriter.cpp \
           require/qtpdfium/src/pdfium/qpdfium.cpp \
           require/qtpdfium/src/pdfium/qpdfiumglobal.cpp \
           require/qtpdfium/src/pdfium/qpdfiumpage.cpp
